[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700
username=supervisor
password={SHA}5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8

[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
username=supervisor
password=password

[program:php-fpm]
command=/usr/local/sbin/php-fpm --nodaemonize --force-stderr
priority=10
autostart=true
autorestart=true
startsecs=2
stopsignal=QUIT
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:wp-cron]
command=/usr/local/bin/wp-cron-runner
priority=20
autostart=true
autorestart=true
startsecs=2
startretries=3
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
